---
title: "Car model"
author: "sergey"
date: "March 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(randomForest)
library(caret)
```

```{r prepare volkswagen data, warning = FALSE, message=FALSE}
source("./data-clean.R")
vw <- clean_auto[clean_auto[, "brand"] == "volkswagen", ]
# remove NAs
vw <- vw[complete.cases(vw), ]
# convert y to factor
vw$model <- as.factor(vw$model)
# remove columns:
vw <- vw[, -which(colnames(vw) %in% 
                    c("Longitude", "Latitude", "postalCode", 
                      "State.Abbreviation", "brand", "name"))]
# number of models to predict:
length(unlist(unique(vw[, "model"])))
```
## datasets
``` {r vw datasets }
inTrain <- createDataPartition(y = vw$model, p=0.75, list=FALSE)
training <- vw[inTrain, ]
testing <- vw[-inTrain, ]
dim(training)
```

## Classification tree RPART 
``` {r rpart}
modFit <- train(model ~ ., method = "rpart", data=training)
pred <- predict (modFit, newdata = testing)
confusionMatrix(pred, testing$model)
```

## random forest
``` {r random forest}
#training
modFit <- randomForest(model ~ ., method = "rpart", data=training)
#predicting
pred <- predict (modFit, newdata = testing)
#results
confusionMatrix(pred, testing$model)
```

## boosting
``` {r boosting}
#small sample
vw_sm <- vw[sample(nrow(vw), size = 3000), ]
inTrain_sm <- createDataPartition(y = vw_sm$model, p=0.75, list=FALSE)
training_sm <- vw_sm[inTrain_sm, ]
testing_sm <- vw_sm[-inTrain_sm, ]

#training
modFit <- train(model ~ ., method = "gbm", data=training_sm, verbose = FALSE)
#predicting
pred <- predict (modFit, newdata = testing_sm)
#results
confusionMatrix(pred, testing_sm$model)

```