---
title: "Missing data exploration"
author: "sergey"
date: "April 24, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r source files, echo=FALSE}
source("./R/ML_utils.R")
source("./R/data-clean.R")
```

## Data in a nutschell
```{r data, echo=FALSE}
print(str(autodata()))
```

## Number of NA's in every column we're interested in
### ("price", "vehicleType", "yearOfRegistration", "gearbox", "powerPS", "brand", "model", "kilometer", "fuelType", "notRepairedDamage")
```{r NA total, echo=FALSE}
vars <- c("price", "vehicleType", "yearOfRegistration", "gearbox", "powerPS", "brand", "model", "kilometer", "fuelType", "notRepairedDamage")

numNA = sapply(vars, FUN = function(v)sum(is.na(autoData()[, v])))
(numNA[numNA != 0])
```

## Observations with all NAs in sought-for columns
```{r}
#get row indecies where all selected columns have NA
idxAllNAs <- function(data, colnames) {
  Reduce(intersect, 
         sapply(colnames, 
             FUN = function(nam) {
               which(is.na(data[, nam]))
             },
             simplify = FALSE))
}

allNA <- idxAllNAs(autoData(), names(numNA[numNA != 0]))
print(length(allNA))
```

## Which (how many of) NAs are impossible to predict
```{r}
sapply(names(numNA[numNA != 0]), 
       FUN = function(nam) {
         idxAllNAs(autoData(), 
                   setdiff(names(numNA[numNA != 0]), nam)) #skip this column
       },
       simplify = FALSE) -> impos

print(sum(sapply(impos, length)))
```

