---
title: "Model choosing for a car model prediction"
author: "sergey"
date: "March 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(randomForest)
library(caret)
```

```{r prepare volkswagen data, warning = FALSE, message=FALSE}
source("./data-clean.R")
source("./ML_utils.R")
vw <- getBrandDataset(clean_auto, "volkswagen")
# number of models to predict:
length(unlist(unique(vw[, "model"])))
```
## datasets
``` {r vw datasets }
#small dataset
dataset <- vw[sample(nrow(vw), size = 4000), ]

#inTrain <- createDataPartition(y = dataset$model, p=0.75, list=FALSE)
#training <- dataset[inTrain, ]
#testing <- dataset[-inTrain, ]
```

``` {r prepare}
seed <- 798
metric <- "Accuracy"
control <- trainControl(method="cv", number=4)
```


## learning 
``` {r learning}
system.time({
  print(system.time({
    set.seed(seed)
    modPart <- train(model ~ ., method = "rpart", metric = metric, data = dataset, trControl = control)
  }))
  print(system.time({
    set.seed(seed)
    modRF <- train(model ~ ., method = "rf", metric = metric, data = dataset, trControl = control)
  }))
  print(system.time({
    set.seed(seed)
    modC50 <- train(model ~ ., method = "C5.0", metric = metric, data = dataset, trControl = control)
  }))
  print(system.time({
    set.seed(seed)
    modBag <- train(model ~ ., method = "treebag", metric = metric, data = dataset, trControl = control)
  }))
  print(system.time({
    set.seed(seed)
#    modGBM <- train(model ~ ., method = "gbm", metric = metric, data = dataset, trControl = control)
  }))
  print(system.time({
    set.seed(seed)
    modJ48 <- train(model ~ ., method = "J48", metric = metric, data = dataset, trControl = control)
  }))
  print(system.time({
    set.seed(seed)
#    modAda <- train(model ~ ., method = "adaboost", metric = metric, data = dataset, trControl = control)
  }))
  print(system.time({
    set.seed(seed)
    modPART <- train(model ~ ., method = "PART", metric = metric, data = dataset, trControl = control)
  }))
  
  results <- resamples(list(
      rpart = modFit,
      rf = modRF,
      c50 = modC50,
      bagging = modBag
#      ,GBM = modGBM
      ,J48 = modJ48
#      ,Ada = modAda
      ,PART = modPART
    ))
})
summary(results)
```

## plot
``` {r figures}
# boxplot comparison
bwplot(results)
# Dot-plot comparison
dotplot(results)
```
